name: Release

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "y" to confirm merging develop into master'
        required: true
permissions:
  contents: write

jobs:
  push_to_master:
    runs-on: ubuntu-latest
    name: "fast-forward develop to main"
    outputs:
      version: ${{ steps.bump.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: 'master'
    - name: Fast Forward Merge To Master
      uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
      with:
        branchtomerge: origin/develop
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@master
      id: bump
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog_increment_filename: release_body.md
    - name: Fast Forward Merge To Develop
      uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
      with:
        branchtomerge: master
        branch: develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Body
      uses: actions/upload-artifact@v4
      with:
        name: release-body.md
        path: release_body.md

  release:
    needs: push_to_master
    runs-on: ubuntu-latest
    name: "Create Release"
    steps:
    - name: Download Release Body
      uses: actions/download-artifact@v4
      with:
        name: release-body.md
        path: .
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_body.md
        tag_name: ${{ needs.push_to_master.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
