name: Release

on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  release_version:
    runs-on: ubuntu-latest
    name: "Bump version, create changelog and release"

    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fetch-depth: 0
        ref: 'develop'

    - name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@master
      id: bump
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog_increment_filename: release_body.md

    - name: Merge Fast Forward
      uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
      with:
        # Branch to merge
        branchtomerge: develop
        # Branch that will be updated
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
