name: Release

on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  release_version:
    runs-on: ubuntu-latest
    name: "Bump version, create changelog and release"

    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fetch-depth: 0
        ref: 'develop'

    - name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@master
      id: bump
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog_increment_filename: release_body.md

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build package
      run: |
        python -m build

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_body.md
        tag_name: ${{ env.REVISION }}
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge Fast Forward
      uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
      with:
        # Branch to merge
        branchtomerge: develop
        # Branch that will be updated
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
