name: Test

on:
  workflow_run:
    workflows: [Update to Latest Packages]
    types: [completed]
  workflow_dispatch:

jobs:
  succeed:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Succeed
      run: echo "Succeed"
  skip:
    runs-on: ubuntu-latest
    if: ${{ cancelled() }}
    steps:
    - name: Skip
      run: echo "Skip"
  succeed_or_skip:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
    - name: Succeed or Skip
      run: echo "Succeed or Skip"
  
